export const carl_jung_quotes = [
  "Knowing your own darkness is the best method for dealing with the darknesses of other people",
  "The shadow is the negative side of the ego… it is our inner devil, the personification of evil",
  "Until you make the unconscious conscious, it will direct your life, and you will call it fate",
  "In all chaos, there is a cosmos, in all disorder a secret order",
  "People will do anything, no matter how absurd, in order to avoid facing their own souls",
  "As far as we can discern, the sole purpose of human existence is to kindle a light in the darkness of mere being",
  "There is no coming to consciousness without pain",
  "The greatest and most important problems of life are all fundamentally insoluble. They can never be solved but only outgrown",
  "Neurosis is always a substitute for legitimate suffering",
  "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed",
  "Thinking is difficult; that’s why most people judge",
  "Your vision will become clear only when you look into your heart … Who looks outside dreams; who looks inside awakens",
  "It all depends on how we look at things, and not on how they are in themselves",
  "The least of things with a meaning is worth more in life than the greatest of things without it",
  "The shoe that fits one person pinches another; there is no recipe for living that suits all cases",
  "What you resist not only persists but will grow in size",
  "Knowing your shadow self is vital if you wish to bring harmony into your life",
];
